site_name: The Studio Learning Center
site_url: http://localhost:8000/
theme:
  name: material
  logo: assets/logo.svg
  palette:
    scheme: default
    primary: white
    accent: pink
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2024 Bemis Public Library — City of Littleton CO
extra:
  generator: false
plugins:
  - privacy
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format