site_name: The Studio Docs
site_url: http://localhost:8000/
theme:
  name: material
  logo: assets/logo.svg
  palette:
    primary: custom
extra_css:
  - stylesheets/extra.css
extra:
  generator: false