site_name: The Studio Learning Center
site_url: https://wortheybemispldemo.z19.web.core.windows.net/
theme:
  name: material
  logo: assets/logo.svg
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.expand
  favicon: assets/favicon-32x32.png
  palette:
    scheme: default
    primary: white
    accent: pink
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2024 Charlotte Worthey — This is volunteer work done by Charlotte Worthey and does not represent Littleton Bemis Public Library or the docs in its final form.
extra:
  generator: false
plugins:
  - privacy
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - tables
